### ISSUE TITLE
Attempting to run on modern Linux (Pop OS)

### ISSUE THREAD

**Issue by nickheyer** [HudsonGTV/STILLALI#1]
Out of curiosity and with little to no experience with BASIC, I tried to run this using the "Brandy" Basic interpreter for linux (passing the code to Brandy via "-chain ./stillali.bas" cmd arg). 

Unfortunately, it doesn't seem to like it. Maybe I'm missing something. 
![image](https://user-images.githubusercontent.com/60236014/211645608-3b29b775-f09d-41ee-a624-5020357e983d.png)

**Comment by HudsonGTV** [comment]
Hello,

This code is designed to only run after being compiled via QuickBASIC. It will not run in a normal BASIC interpreter, as QuickBASIC implements additional functionality. I am not familiar with the Brandy Basic interpreter, but it appears it is almost certainly not compatible with it.

If you would like to compile this code yourself (on a modern computer), I would recommend that you install DOSBox on your computer. From there, install the Microsoft QuickBASIC (I used version 4.50) IDE. You should be able to run the program from the IDE, or compile it to an EXE which can be run in DOSBox.

There are currently no plans to convert this to work with "normal" BASIC as this project was designed specifically to run on vintage 16-bit x86 based computers.

-Hudson
